version: '3.8'
services:
  app:
    container_name: nestjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:8089'
    environment:
      - MONGODB_URI
      - MONGO_INITDB_DATABASE
    networks:
      - app-network
    depends_on:
      - mongo

  mongo:
    container_name: mongo-db
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - '27017:27017'
    networks:
      - app-network
    volumes:
      - ./data:/data/db

networks:
  app-network:
    driver: bridge